[project]
name = "lenlab"
version = "8.0b0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyside6>=6.8.0.2",
]

[dependency-groups]
dev = [
    "pytest>=8.3.3",
]
